---
server:
    install: '1'
    packages: [vim, htop, iotop]
    timezone: UTC
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.30.10, memory: '1024', sharedfolder: ./, enableWindows: '1', useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /vagrant
    servername: myApp.vb
apache:
    install: '1'
    docroot: /vagrant
    servername: myApp.vb
mysql:
    install: '1'
    root_password: password
    database: db
    user: user
    password: password
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-mysql]
xdebug:
    install: '1'
blackfire:
    install: '1'
    server_id: XXX
    server_token: XXX
